### ISSUE TITLE
Youtube and game websites don't work

### ISSUE THREAD

**Issue by Pizza20** [Degenerate0001/Degeneracy#4]
I have tried all the options and for youtube something always breaks and nothing plays and for the games it says unity error something something something I kind of forgot.

Also for the searx thing that it takes me to when there is no url in the box. If you try to click on images it takes a lot to get it to actually select the images button.

**Comment by Degenerate0001** [comment]
Thank you for this issue report. I will attempt to resolve these issues soon :D
