### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by owenwentzel30** [Degenerate0001/Degeneracy#7]
Cloudflare wont redirect and it's been happening for like 2 days.
![Screenshot 2022-01-20 114419](https://user-images.githubusercontent.com/93006616/150383337-7ff17b7e-0180-4c21-83a5-df8cea099ae2.png)

**Comment by Degenerate0001** [comment]
Does this only happen on [pleasedontblock.me](https://pleasedontblock.me) or does it happen on all Degeneracy links?

**Comment by owenwentzel30** [comment]
Just pleasedontblock.me

**Comment by Degenerate0001** [comment]
I think I have enhanced protection on a bit on that one. Try a different one if possible. I'll look into this on pleasedontblock.me and I'll try to make it not do that.
